### ISSUE TITLE
bruh you stole my code

### ISSUE THREAD

**Issue by Rainb0wSkeppy** [SandboxSB/private-bot#1]

**Comment by 1ToastyBred1** [comment]
Of course SB cant write such stuff

**Comment by Rainb0wSkeppy** [comment]
**THAT IS LITERALLY MY CODE**
sb is a 8 year old kid that cant write code 
also @Albondows DID YOU GIVE THIS KID MY CODE

**Comment by 1ToastyBred1** [comment]
lol

**Comment by SandboxSB** [comment]
You went into my GitHub account to insult me, while I was coding. By the way fuck off you dumb ass moron, I do not care that I stole your code, I used them for my servers. You piece of a shit, of course I'm a 8 years old for saying this. But in fact you're more immature like go get a fucking life you dumbass moron @Martsadas, you gotta get a brain before saying somebody is a kid. You call somebody a kid who knows everything than your brain saying mOmmY! hE stOlE mY cOdES!1!

**Comment by SandboxSB** [comment]
In fact, @Goldberg123456, Nobody likes you for your action on me. I know everyone hates me on classicube for running a server, you dumb bastard. Get the fuck out of my GitHub account, you don't have the authority to comment.

**Comment by SandboxSB** [comment]
> **THAT IS LITERALLY MY CODE** sb is a 8 year old kid that cant write code also @Albondows DID YOU GIVE THIS KID MY CODE

Yep, he gave me everything, get the fuck out of here you dumb moron. You insulted me something like LGBT dumbass community would say.

**Comment by SandboxSB** [comment]
> Of course SB cant write such stuff

Of course you don't have feelings for your friend, you'd rather support a moron called ilikebinz who has been being an clown for whole time just like LGBT does to your friend.

**Comment by SandboxSB** [comment]
Although I did steal your `code` but, now I'm gonna edit the code. and add some features to it, because you called me a skiddo. Like shut the fuck up you stupid moron, you ain't humiliating me bruv, by the way @Goldberg123456 Weeb skid, you told him that I stole his code, yes that's true. But I'm gonna add features to it, and change credits. Because I don't like you jerks trying to humiliate me, Why soo mad over a code? Huh? This is not what you will get in death. Anyways stop being an weeb already you two morons @Martsadas @Goldberg123456

**Comment by 1ToastyBred1** [comment]
btw what features are you gonna add? just curious

**Comment by Rainb0wSkeppy** [comment]
`ratio`

**Comment by 1ToastyBred1** [comment]
"Note: This is not @Martadas's bot code anymore, there will be features that were included in the You can't do Part. That's called! stealing!! Stop!! I know it's stealing, but today i decided to edit the code, adding features. No time for your drama, go use your brain you dumb moron." - it will be always his code tho, unless u start your own bot so why dont you make your own bot?

**Comment by SandboxSB** [comment]
Good idea, I can start my own bot, but now Martadas's bot is not his bot anymore, fuck off. piss shit, I knew that the situation will happen somehow, and one ratio won't stop me. there's one loser called Gayberg, @Martsadas, Get the fuck out of my account. you moron, My features? @Goldberg123456 This is none of your business you fucking moron bastard.

**Comment by SandboxSB** [comment]
Looks like, you're trying to get me hated, but i do not give a fuck somehow. I did steal it, I also know your plans, you asked albo that if he sent that to me, then goes this loser martagay tries to insult like a bozo, L + bozo.

**Comment by SandboxSB** [comment]
Lol? Silent? Yeah, looks like i win, fuck off dude really named himself Goldberg, what you gonna do? Fucking moron tries to scare me with his report button ahh ahh
